package org.framefork.typedIds.bigint.springData;

import org.framefork.typedIds.bigint.hibernate.basic.BigIntDbAutoGeneratedExplicitMappingEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface BigIntDbAutoGeneratedExplicitMappingEntityRepository extends JpaRepository<BigIntDbAutoGeneratedExplicitMappingEntity, BigIntDbAutoGeneratedExplicitMappingEntity.Id>
{

    BigIntDbAutoGeneratedExplicitMappingEntity findByTitle(String title);

}
