package org.framefork.typedIds.embeddable;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import org.jspecify.annotations.Nullable;

@Entity
@Table(name = EntityEmbeddableBigIntGeneratedId.TABLE_NAME)
public class EntityEmbeddableBigIntGeneratedId
{

    public static final String TABLE_NAME = "embeddable_generated_id";

    @EmbeddedId
    @Nullable
    private EmbeddableBigIntWithGenerated id;

    @Column(nullable = false)
    private String name;

    public EntityEmbeddableBigIntGeneratedId(String name)
    {
        this.name = name;
        // Note: id should be generated by Hibernate, but will it work with @EmbeddedId?
    }

    @SuppressWarnings("NullAway")
    protected EntityEmbeddableBigIntGeneratedId()
    {
    }

    @Nullable
    public EmbeddableBigIntWithGenerated getId()
    {
        return id;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

}
