name: Run Checks via Gradle

on:
  push:
    branches:
      - master
  pull_request:

env:
  GRADLE_OPTS: "-Dorg.gradle.console=plain -Dorg.gradle.daemon=false -Dorg.gradle.stacktrace=always"

jobs:
  gradle:
    strategy:
      matrix:
        java: [17, 21, 22, 23]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary-as-pr-comment: on-failure

      - name: Gradle build environment info
        run: ./gradlew -q buildEnvironment

      - name: Execute Gradle build
        run: ./gradlew --continue build

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: junit-test-results
          path: '**/build/test-results/test/TEST-*.xml'
          retention-days: 1
          overwrite: true
